#!/usr/bin/env python3
"""HTTP request/response logging middleware generator.

Generates production-ready middleware code for popular frameworks that logs
every HTTP request and response with timing, headers, status, body size,
correlation IDs, and error details.

Usage:
    python3 network_request_logger.py generate --framework fastapi --output middleware.py
    python3 network_request_logger.py generate --framework express --output middleware.ts
    python3 network_request_logger.py generate --framework flask
    python3 network_request_logger.py analyze <access.log> [--format report]
"""

import sys
import re
import json
import argparse
from pathlib import Path
from collections import Counter, defaultdict
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Optional
from datetime import datetime

FASTAPI_MIDDLEWARE = '''"""
HTTP Request/Response Logging Middleware for FastAPI.
Generated by enterprise-deep-debug/network_request_logger.py

Logs every request with: method, path, status, timing, headers, body size,
client IP, correlation ID, and error details.
"""
import uuid
import time
import logging
import structlog
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response
from structlog.contextvars import bind_contextvars, clear_contextvars

logger = structlog.get_logger("http")

SENSITIVE_HEADERS = frozenset({"authorization", "cookie", "set-cookie", "x-api-key", "x-auth-token"})
SKIP_PATHS = frozenset({"/health", "/healthz", "/ready", "/metrics", "/favicon.ico"})


def _safe_headers(headers: dict) -> dict:
    return {k: ("[REDACTED]" if k.lower() in SENSITIVE_HEADERS else v)
            for k, v in headers.items()}


class HTTPLoggingMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        if request.url.path in SKIP_PATHS:
            return await call_next(request)

        clear_contextvars()
        request_id = request.headers.get("X-Request-ID", str(uuid.uuid4())[:12])

        bind_contextvars(
            request_id=request_id,
            http_method=request.method,
            http_path=str(request.url.path),
            http_query=str(request.query_params) if request.query_params else None,
            client_ip=request.client.host if request.client else "unknown",
            user_agent=request.headers.get("user-agent", "")[:100],
        )

        start = time.perf_counter()
        content_length_in = request.headers.get("content-length", "0")

        logger.info("http_request_start",
                     request_headers=_safe_headers(dict(request.headers.items())))

        try:
            response = await call_next(request)
            elapsed_ms = round((time.perf_counter() - start) * 1000, 2)
            content_length_out = response.headers.get("content-length", "?")

            log_method = logger.info if response.status_code < 400 else (
                logger.warning if response.status_code < 500 else logger.error
            )

            log_method("http_request_complete",
                       http_status=response.status_code,
                       elapsed_ms=elapsed_ms,
                       request_bytes=content_length_in,
                       response_bytes=content_length_out,
                       response_headers=_safe_headers(dict(response.headers.items())))

            response.headers["X-Request-ID"] = request_id
            response.headers["X-Response-Time"] = f"{elapsed_ms}ms"
            return response

        except Exception as exc:
            elapsed_ms = round((time.perf_counter() - start) * 1000, 2)
            logger.error("http_request_error",
                         error_type=type(exc).__name__,
                         error_message=str(exc)[:500],
                         elapsed_ms=elapsed_ms,
                         exc_info=True)
            raise
'''

EXPRESS_MIDDLEWARE = """/**
 * HTTP Request/Response Logging Middleware for Express.
 * Generated by enterprise-deep-debug/network_request_logger.py
 */
import { Request, Response, NextFunction } from 'express';
import pino from 'pino';

const logger = pino({ name: 'http' });

const SENSITIVE_HEADERS = new Set(['authorization', 'cookie', 'set-cookie', 'x-api-key']);
const SKIP_PATHS = new Set(['/health', '/healthz', '/ready', '/metrics', '/favicon.ico']);

function safeHeaders(headers: Record<string, string | string[] | undefined>): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(headers)) {
    if (value === undefined) continue;
    result[key] = SENSITIVE_HEADERS.has(key.toLowerCase()) ? '[REDACTED]' : String(value).slice(0, 200);
  }
  return result;
}

export function httpLoggingMiddleware(req: Request, res: Response, next: NextFunction): void {
  if (SKIP_PATHS.has(req.path)) { next(); return; }

  const requestId = (req.headers['x-request-id'] as string) || crypto.randomUUID().slice(0, 12);
  const start = performance.now();

  const child = logger.child({
    requestId,
    method: req.method,
    path: req.path,
    query: req.query,
    clientIp: req.ip || req.socket.remoteAddress,
    userAgent: req.headers['user-agent']?.slice(0, 100),
  });

  child.info({ requestHeaders: safeHeaders(req.headers as any) }, 'http_request_start');

  const originalEnd = res.end;
  res.end = function(...args: any[]) {
    const elapsed = (performance.now() - start).toFixed(2);
    const logMethod = res.statusCode < 400 ? child.info.bind(child) :
                      res.statusCode < 500 ? child.warn.bind(child) : child.error.bind(child);

    logMethod({
      status: res.statusCode,
      elapsed_ms: parseFloat(elapsed),
      responseHeaders: safeHeaders(res.getHeaders() as any),
      contentLength: res.getHeader('content-length'),
    }, 'http_request_complete');

    res.setHeader('X-Request-ID', requestId);
    res.setHeader('X-Response-Time', `${elapsed}ms`);
    return originalEnd.apply(this, args);
  } as any;

  next();
}

export default httpLoggingMiddleware;
"""

FLASK_MIDDLEWARE = '''"""
HTTP Request/Response Logging Middleware for Flask.
Generated by enterprise-deep-debug/network_request_logger.py
"""
import uuid
import time
import structlog
from flask import Flask, request, g
from structlog.contextvars import bind_contextvars, clear_contextvars

logger = structlog.get_logger("http")

SKIP_PATHS = frozenset({"/health", "/healthz", "/ready", "/metrics"})


def setup_http_logging(app: Flask):
    @app.before_request
    def log_request_start():
        if request.path in SKIP_PATHS:
            return

        clear_contextvars()
        g.request_id = request.headers.get("X-Request-ID", str(uuid.uuid4())[:12])
        g.start_time = time.perf_counter()

        bind_contextvars(
            request_id=g.request_id,
            http_method=request.method,
            http_path=request.path,
            client_ip=request.remote_addr,
        )
        logger.info("http_request_start")

    @app.after_request
    def log_request_end(response):
        if request.path in SKIP_PATHS:
            return response

        elapsed_ms = round((time.perf_counter() - getattr(g, "start_time", time.perf_counter())) * 1000, 2)
        log_method = logger.info if response.status_code < 400 else logger.error

        log_method("http_request_complete",
                   http_status=response.status_code,
                   elapsed_ms=elapsed_ms,
                   response_bytes=response.content_length)

        response.headers["X-Request-ID"] = getattr(g, "request_id", "")
        response.headers["X-Response-Time"] = f"{elapsed_ms}ms"
        return response

    @app.errorhandler(Exception)
    def log_error(error):
        elapsed_ms = round((time.perf_counter() - getattr(g, "start_time", time.perf_counter())) * 1000, 2)
        logger.error("http_request_error",
                     error_type=type(error).__name__,
                     error_message=str(error)[:500],
                     elapsed_ms=elapsed_ms,
                     exc_info=True)
        raise error
'''

FRAMEWORKS = {
    "fastapi": ("python", FASTAPI_MIDDLEWARE, "middleware.py"),
    "flask": ("python", FLASK_MIDDLEWARE, "http_logging.py"),
    "express": ("typescript", EXPRESS_MIDDLEWARE, "httpLogging.ts"),
}


@dataclass
class AccessLogEntry:
    timestamp: Optional[str]
    method: str
    path: str
    status: int
    response_time_ms: float
    size_bytes: int


def analyze_access_log(filepath: Path) -> Dict:
    combined_re = re.compile(
        r'(\S+)\s+\S+\s+\S+\s+\[(.+?)\]\s+"(\S+)\s+(\S+)\s+\S+"\s+(\d+)\s+(\d+)'
    )
    timing_re = re.compile(r"(\d+(?:\.\d+)?)\s*(?:ms|s)")

    entries: List[AccessLogEntry] = []
    for line in filepath.read_text(errors="replace").splitlines():
        m = combined_re.match(line)
        if m:
            method = m.group(3)
            path = m.group(4)
            status = int(m.group(5))
            size = int(m.group(6))
            tm = timing_re.search(line)
            response_time = float(tm.group(1)) if tm else 0
            entries.append(
                AccessLogEntry(
                    timestamp=m.group(2),
                    method=method,
                    path=path,
                    status=status,
                    response_time_ms=response_time,
                    size_bytes=size,
                )
            )

    if not entries:
        return {"error": "No parseable access log entries found"}

    status_counts = Counter(e.status for e in entries)
    path_counts = Counter(e.path for e in entries)
    slow_requests = sorted(entries, key=lambda e: e.response_time_ms, reverse=True)[:20]
    error_requests = [e for e in entries if e.status >= 400]

    return {
        "total_requests": len(entries),
        "status_distribution": dict(status_counts.most_common()),
        "top_paths": dict(path_counts.most_common(20)),
        "error_count": len(error_requests),
        "error_rate_pct": round(len(error_requests) / len(entries) * 100, 2),
        "avg_response_ms": round(
            sum(e.response_time_ms for e in entries) / len(entries), 2
        ),
        "p95_response_ms": round(
            sorted(e.response_time_ms for e in entries)[int(len(entries) * 0.95)], 2
        )
        if entries
        else 0,
        "slowest_requests": [asdict(e) for e in slow_requests[:10]],
    }


def main():
    parser = argparse.ArgumentParser(
        description="HTTP request/response logging middleware generator"
    )
    subparsers = parser.add_subparsers(dest="command")

    gen_p = subparsers.add_parser("generate", help="Generate middleware code")
    gen_p.add_argument("--framework", required=True, choices=list(FRAMEWORKS.keys()))
    gen_p.add_argument("--output", help="Output file path")

    analyze_p = subparsers.add_parser("analyze", help="Analyze access logs")
    analyze_p.add_argument("logfile")
    analyze_p.add_argument("--format", choices=["json", "report"], default="report")

    args = parser.parse_args()

    if args.command == "generate":
        lang, code, default_name = FRAMEWORKS[args.framework]
        output = args.output or default_name
        Path(output).write_text(code)
        print(f"Generated {args.framework} middleware: {output}")

    elif args.command == "analyze":
        result = analyze_access_log(Path(args.logfile))
        if args.format == "json":
            print(json.dumps(result, indent=2))
        else:
            print(f"Total requests: {result.get('total_requests', 0)}")
            print(f"Error rate: {result.get('error_rate_pct', 0)}%")
            print(f"Avg response: {result.get('avg_response_ms', 0)}ms")
            print(f"P95 response: {result.get('p95_response_ms', 0)}ms")
            if result.get("status_distribution"):
                print("Status codes:", result["status_distribution"])
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
