#!/usr/bin/env python3
"""OpenTelemetry auto-instrumentation bootstrapper.

Detects installed packages and generates the correct OTel setup code for
zero-code instrumentation. Handles Python and Node.js projects.

Usage:
    python3 otel_bootstrapper.py detect <project_dir>
    python3 otel_bootstrapper.py setup <project_dir> [--service-name myapp] [--exporter console|otlp|jaeger]
    python3 otel_bootstrapper.py verify <project_dir>
"""

import sys
import json
import subprocess
import argparse
from pathlib import Path
from typing import Dict, List, Optional

PYTHON_OTEL_PACKAGES = {
    "flask": "opentelemetry-instrumentation-flask",
    "fastapi": "opentelemetry-instrumentation-fastapi",
    "django": "opentelemetry-instrumentation-django",
    "requests": "opentelemetry-instrumentation-requests",
    "httpx": "opentelemetry-instrumentation-httpx",
    "aiohttp": "opentelemetry-instrumentation-aiohttp-client",
    "sqlalchemy": "opentelemetry-instrumentation-sqlalchemy",
    "psycopg2": "opentelemetry-instrumentation-psycopg2",
    "redis": "opentelemetry-instrumentation-redis",
    "celery": "opentelemetry-instrumentation-celery",
    "grpc": "opentelemetry-instrumentation-grpc",
    "boto3": "opentelemetry-instrumentation-boto3sqs",
    "pymongo": "opentelemetry-instrumentation-pymongo",
    "elasticsearch": "opentelemetry-instrumentation-elasticsearch",
    "urllib3": "opentelemetry-instrumentation-urllib3",
    "logging": "opentelemetry-instrumentation-logging",
}

PYTHON_OTEL_SETUP = '''#!/usr/bin/env python3
"""OpenTelemetry auto-instrumentation setup.
Generated by enterprise-deep-debug/otel_bootstrapper.py

Run your application with:
    opentelemetry-instrument python app.py
Or import this module at application startup.
"""
import os
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.sdk.resources import Resource, SERVICE_NAME
from opentelemetry.propagate import set_global_textmap
from opentelemetry.propagators.composite import CompositePropagator
from opentelemetry.trace.propagation import TraceContextTextMapPropagator
from opentelemetry.baggage.propagation import W3CBaggagePropagator

SERVICE = os.getenv("OTEL_SERVICE_NAME", "{service_name}")
EXPORTER_TYPE = os.getenv("OTEL_EXPORTER", "{exporter}")


def setup_tracing():
    resource = Resource.create({{
        SERVICE_NAME: SERVICE,
        "deployment.environment": os.getenv("ENVIRONMENT", "development"),
    }})

    provider = TracerProvider(resource=resource)

    if EXPORTER_TYPE == "otlp":
        from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
        exporter = OTLPSpanExporter(
            endpoint=os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:4317"),
        )
    elif EXPORTER_TYPE == "jaeger":
        from opentelemetry.exporter.jaeger.thrift import JaegerExporter
        exporter = JaegerExporter(
            agent_host_name=os.getenv("JAEGER_HOST", "localhost"),
            agent_port=int(os.getenv("JAEGER_PORT", "6831")),
        )
    else:
        from opentelemetry.sdk.trace.export import ConsoleSpanExporter
        exporter = ConsoleSpanExporter()

    provider.add_span_processor(BatchSpanProcessor(exporter))
    trace.set_tracer_provider(provider)

    set_global_textmap(CompositePropagator([
        TraceContextTextMapPropagator(),
        W3CBaggagePropagator(),
    ]))

    return trace.get_tracer(SERVICE)


tracer = setup_tracing()
'''

NODE_OTEL_SETUP = """// OpenTelemetry auto-instrumentation setup
// Generated by enterprise-deep-debug/otel_bootstrapper.py
//
// Add to your app startup: import './otel_setup';
// Or run with: node --require ./otel_setup.js app.js

import {{ NodeSDK }} from '@opentelemetry/sdk-node';
import {{ getNodeAutoInstrumentations }} from '@opentelemetry/auto-instrumentations-node';
import {{ Resource }} from '@opentelemetry/resources';
import {{ ATTR_SERVICE_NAME }} from '@opentelemetry/semantic-conventions';

const SERVICE_NAME = process.env.OTEL_SERVICE_NAME || '{service_name}';

const sdk = new NodeSDK({{
  resource: new Resource({{
    [ATTR_SERVICE_NAME]: SERVICE_NAME,
  }}),
  instrumentations: [getNodeAutoInstrumentations({{
    '@opentelemetry/instrumentation-fs': {{ enabled: false }},
  }})],
}});

sdk.start();

process.on('SIGTERM', () => {{
  sdk.shutdown().then(() => process.exit(0)).catch(() => process.exit(1));
}});

console.log(`OpenTelemetry initialized for ${{SERVICE_NAME}}`);
"""


def detect_python_deps(project_dir: Path) -> List[str]:
    installed = []
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "list", "--format=json"],
            capture_output=True,
            text=True,
            timeout=15,
        )
        if result.returncode == 0:
            packages = {p["name"].lower() for p in json.loads(result.stdout)}
            for lib, otel_pkg in PYTHON_OTEL_PACKAGES.items():
                if lib in packages:
                    installed.append(
                        {
                            "library": lib,
                            "otel_package": otel_pkg,
                            "installed": otel_pkg.lower().replace("-", "_") in packages
                            or otel_pkg.lower() in packages,
                        }
                    )
    except Exception:
        for dep_file in [
            project_dir / "requirements.txt",
            project_dir / "pyproject.toml",
        ]:
            if dep_file.exists():
                content = dep_file.read_text().lower()
                for lib, otel_pkg in PYTHON_OTEL_PACKAGES.items():
                    if lib in content:
                        installed.append(
                            {
                                "library": lib,
                                "otel_package": otel_pkg,
                                "installed": False,
                            }
                        )

    return installed


def detect_node_deps(project_dir: Path) -> List[str]:
    pkg_json = project_dir / "package.json"
    if not pkg_json.exists():
        return []

    try:
        pkg = json.loads(pkg_json.read_text())
        all_deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
        has_otel = "@opentelemetry/sdk-node" in all_deps
        has_auto = "@opentelemetry/auto-instrumentations-node" in all_deps
        return [
            {
                "has_otel_sdk": has_otel,
                "has_auto_instrumentations": has_auto,
                "all_deps": list(all_deps.keys()),
            }
        ]
    except Exception:
        return []


def setup_project(
    project_dir: Path, service_name: str, exporter: str, language: str = None
) -> Dict:
    result = {"files_created": [], "packages_to_install": [], "run_command": ""}

    if language == "python" or (language is None and list(project_dir.rglob("*.py"))):
        config = PYTHON_OTEL_SETUP.format(service_name=service_name, exporter=exporter)
        out_file = project_dir / "otel_setup.py"
        out_file.write_text(config)
        result["files_created"].append(str(out_file))

        deps = detect_python_deps(project_dir)
        packages = ["opentelemetry-distro", "opentelemetry-exporter-otlp"]
        for d in deps:
            if not d.get("installed"):
                packages.append(d["otel_package"])
        result["packages_to_install"] = packages
        result["install_command"] = f"pip install {' '.join(packages)}"
        result["run_command"] = f"opentelemetry-instrument python app.py"
        result["bootstrap_command"] = "opentelemetry-bootstrap -a install"

    elif language == "node" or (
        language is None and (project_dir / "package.json").exists()
    ):
        config = NODE_OTEL_SETUP.format(service_name=service_name)
        out_file = project_dir / "otel_setup.ts"
        out_file.write_text(config)
        result["files_created"].append(str(out_file))

        result["packages_to_install"] = [
            "@opentelemetry/sdk-node",
            "@opentelemetry/api",
            "@opentelemetry/auto-instrumentations-node",
            "@opentelemetry/resources",
            "@opentelemetry/semantic-conventions",
        ]
        result["install_command"] = (
            f"npm install {' '.join(result['packages_to_install'])}"
        )
        result["run_command"] = f"node --require ./otel_setup.js app.js"

    return result


def main():
    parser = argparse.ArgumentParser(
        description="OpenTelemetry auto-instrumentation bootstrapper"
    )
    subparsers = parser.add_subparsers(dest="command")

    detect_p = subparsers.add_parser("detect", help="Detect instrumentable libraries")
    detect_p.add_argument("project_dir")

    setup_p = subparsers.add_parser("setup", help="Generate OTel setup files")
    setup_p.add_argument("project_dir")
    setup_p.add_argument("--service-name", default="my-service")
    setup_p.add_argument(
        "--exporter", choices=["console", "otlp", "jaeger"], default="console"
    )
    setup_p.add_argument("--language", choices=["python", "node"])

    verify_p = subparsers.add_parser("verify", help="Verify OTel installation")
    verify_p.add_argument("project_dir")

    args = parser.parse_args()

    if args.command == "detect":
        project_dir = Path(args.project_dir)
        py_deps = detect_python_deps(project_dir)
        node_deps = detect_node_deps(project_dir)
        print(json.dumps({"python": py_deps, "node": node_deps}, indent=2))

    elif args.command == "setup":
        result = setup_project(
            Path(args.project_dir), args.service_name, args.exporter, args.language
        )
        print(json.dumps(result, indent=2))
        if result["packages_to_install"]:
            print(f"\nRun: {result.get('install_command', '')}", file=sys.stderr)
            if result.get("bootstrap_command"):
                print(f"Then: {result['bootstrap_command']}", file=sys.stderr)

    elif args.command == "verify":
        try:
            from opentelemetry import trace

            provider = trace.get_tracer_provider()
            print(f"OTel OK: provider={type(provider).__name__}")
        except ImportError:
            print(
                "OTel NOT installed. Run: pip install opentelemetry-distro",
                file=sys.stderr,
            )
            sys.exit(1)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
