#!/usr/bin/env python3
"""Auto-generates production-grade structured logging configuration.

Detects the project language/framework and generates optimal structlog (Python)
or pino (Node.js) configuration with correlation IDs, exception formatting,
callsite info, and OpenTelemetry trace correlation.

Usage:
    python3 structlog_configurator.py detect <project_dir>
    python3 structlog_configurator.py generate <project_dir> [--framework flask|fastapi|django|express|nextjs]
    python3 structlog_configurator.py generate src/ --python --output logging_config.py
    python3 structlog_configurator.py generate src/ --node --output logger.ts
"""

import sys
import json
import argparse
from pathlib import Path
from typing import Dict, List, Optional, Tuple

PYTHON_STRUCTLOG_CONFIG = '''"""
Auto-generated structured logging configuration.
Generated by enterprise-deep-debug/structlog_configurator.py

Features:
- JSON output in production, colored console in development
- Automatic correlation ID propagation via contextvars
- Exception traceback as structured dict
- Callsite info (file, function, line)
- OpenTelemetry trace/span ID injection (if otel available)
- Timestamp in ISO 8601 format
"""
import logging
import sys
import os
import structlog
from structlog.contextvars import merge_contextvars, bind_contextvars, clear_contextvars

IS_PRODUCTION = os.getenv("ENVIRONMENT", "development").lower() in ("production", "prod", "staging")


def setup_logging(level: str = "DEBUG", json_output: bool = None):
    """Call this once at application startup."""
    if json_output is None:
        json_output = IS_PRODUCTION

    shared_processors = [
        merge_contextvars,
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.UnicodeDecoder(),
        structlog.processors.CallsiteParameterAdder(
            parameters=[
                structlog.processors.CallsiteParameter.FILENAME,
                structlog.processors.CallsiteParameter.FUNC_NAME,
                structlog.processors.CallsiteParameter.LINENO,
            ]
        ),
    ]

    # OpenTelemetry trace correlation (optional)
    try:
        from opentelemetry import trace

        def add_otel_context(logger, method_name, event_dict):
            span = trace.get_current_span()
            if span and span.is_recording():
                ctx = span.get_span_context()
                event_dict["trace_id"] = format(ctx.trace_id, "032x")
                event_dict["span_id"] = format(ctx.span_id, "016x")
            return event_dict

        shared_processors.append(add_otel_context)
    except ImportError:
        pass

    if json_output:
        renderer = structlog.processors.JSONRenderer()
    else:
        renderer = structlog.dev.ConsoleRenderer(
            colors=sys.stderr.isatty(),
            exception_formatter=structlog.dev.plain_traceback,
        )

    structlog.configure(
        processors=[
            *shared_processors,
            structlog.processors.format_exc_info,
            structlog.processors.EventRenamer("msg"),
            renderer,
        ],
        wrapper_class=structlog.stdlib.BoundLogger,
        context_class=dict,
        logger_factory=structlog.stdlib.LoggerFactory(),
        cache_logger_on_first_use=True,
    )

    # Also configure stdlib logging to go through structlog
    formatter = structlog.stdlib.ProcessorFormatter(
        processors=[
            structlog.stdlib.ProcessorFormatter.remove_processors_meta,
            *shared_processors,
            structlog.processors.format_exc_info,
            renderer,
        ],
    )

    handler = logging.StreamHandler(sys.stderr)
    handler.setFormatter(formatter)

    root = logging.getLogger()
    root.handlers.clear()
    root.addHandler(handler)
    root.setLevel(getattr(logging, level.upper(), logging.DEBUG))


def get_logger(name: str = None):
    """Get a structlog logger with the given name."""
    return structlog.get_logger(name)


# Auto-setup if imported
setup_logging()
'''

PYTHON_FASTAPI_MIDDLEWARE = '''
"""Request logging middleware for FastAPI with correlation ID propagation."""
import uuid
import time
import structlog
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from structlog.contextvars import bind_contextvars, clear_contextvars

logger = structlog.get_logger(__name__)


class RequestLoggingMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        clear_contextvars()

        request_id = request.headers.get("X-Request-ID", str(uuid.uuid4())[:8])
        bind_contextvars(
            request_id=request_id,
            method=request.method,
            path=str(request.url.path),
            client=request.client.host if request.client else "unknown",
        )

        start = time.perf_counter()
        logger.info("request_started")

        try:
            response = await call_next(request)
            elapsed = (time.perf_counter() - start) * 1000
            logger.info("request_completed",
                        status=response.status_code,
                        elapsed_ms=round(elapsed, 2))
            response.headers["X-Request-ID"] = request_id
            return response
        except Exception as exc:
            elapsed = (time.perf_counter() - start) * 1000
            logger.error("request_failed",
                         error=str(exc),
                         error_type=type(exc).__name__,
                         elapsed_ms=round(elapsed, 2),
                         exc_info=True)
            raise
'''

NODE_PINO_CONFIG = """// Auto-generated structured logging configuration
// Generated by enterprise-deep-debug/structlog_configurator.py
//
// Features:
// - JSON output in production, pretty print in development
// - Automatic request ID propagation
// - Error serialization with stack traces
// - OpenTelemetry trace correlation
// - Child loggers with bound context

import pino from 'pino';

const IS_PRODUCTION = process.env.NODE_ENV === 'production';

export const logger = pino({
  level: process.env.LOG_LEVEL || (IS_PRODUCTION ? 'info' : 'debug'),
  transport: IS_PRODUCTION ? undefined : {
    target: 'pino-pretty',
    options: {
      colorize: true,
      translateTime: 'SYS:yyyy-mm-dd HH:MM:ss.l',
      ignore: 'pid,hostname',
    },
  },
  serializers: {
    err: pino.stdSerializers.err,
    req: pino.stdSerializers.req,
    res: pino.stdSerializers.res,
  },
  formatters: {
    level: (label: string) => ({ level: label }),
    bindings: (bindings: Record<string, unknown>) => ({
      service: process.env.SERVICE_NAME || 'app',
      ...bindings,
    }),
  },
  timestamp: pino.stdTimeFunctions.isoTime,
  redact: {
    paths: ['req.headers.authorization', 'req.headers.cookie', '*.password', '*.token', '*.secret'],
    censor: '[REDACTED]',
  },
});

// Request logging middleware for Express/Fastify
export function requestLogger(req: any, res: any, next: () => void) {
  const requestId = req.headers['x-request-id'] || crypto.randomUUID().slice(0, 8);
  const start = performance.now();

  req.log = logger.child({ requestId, method: req.method, path: req.url });
  req.log.info('request_started');

  res.on('finish', () => {
    const elapsed = (performance.now() - start).toFixed(2);
    req.log.info({ status: res.statusCode, elapsed_ms: elapsed }, 'request_completed');
  });

  res.setHeader('X-Request-ID', requestId);
  next();
}

export default logger;
"""


def detect_project(project_dir: Path) -> Dict:
    info = {
        "languages": [],
        "frameworks": [],
        "has_logging": False,
        "recommendations": [],
    }

    if list(project_dir.rglob("*.py")):
        info["languages"].append("python")
    if list(project_dir.rglob("*.ts")) or list(project_dir.rglob("*.tsx")):
        info["languages"].append("typescript")
    if list(project_dir.rglob("*.js")) or list(project_dir.rglob("*.jsx")):
        info["languages"].append("javascript")

    pkg_json = project_dir / "package.json"
    if pkg_json.exists():
        try:
            pkg = json.loads(pkg_json.read_text())
            deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
            if "next" in deps:
                info["frameworks"].append("nextjs")
            if "express" in deps:
                info["frameworks"].append("express")
            if "fastify" in deps:
                info["frameworks"].append("fastify")
            if "pino" in deps:
                info["has_logging"] = True
            if "winston" in deps:
                info["has_logging"] = True
        except Exception:
            pass

    req_txt = project_dir / "requirements.txt"
    pyproject = project_dir / "pyproject.toml"
    for dep_file in [req_txt, pyproject]:
        if dep_file.exists():
            content = dep_file.read_text().lower()
            if "fastapi" in content:
                info["frameworks"].append("fastapi")
            if "flask" in content:
                info["frameworks"].append("flask")
            if "django" in content:
                info["frameworks"].append("django")
            if "structlog" in content:
                info["has_logging"] = True

    if "python" in info["languages"] and not info["has_logging"]:
        info["recommendations"].append("Add structlog for structured Python logging")
    if (
        "typescript" in info["languages"] or "javascript" in info["languages"]
    ) and not info["has_logging"]:
        info["recommendations"].append("Add pino for structured Node.js logging")

    return info


def generate_config(
    project_dir: Path, language: str, framework: str = None, output: str = None
) -> str:
    if language == "python":
        config = PYTHON_STRUCTLOG_CONFIG
        if framework in ("fastapi", "flask"):
            config += "\n\n" + PYTHON_FASTAPI_MIDDLEWARE
        out_path = output or "logging_config.py"
    elif language in ("typescript", "javascript", "node"):
        config = NODE_PINO_CONFIG
        out_path = output or "logger.ts"
    else:
        print(f"Unsupported language: {language}", file=sys.stderr)
        sys.exit(1)

    if output:
        out_file = project_dir / out_path
        out_file.write_text(config)
        print(f"Generated {out_file}", file=sys.stderr)

    return config


def main():
    parser = argparse.ArgumentParser(
        description="Auto-generate structured logging configuration"
    )
    subparsers = parser.add_subparsers(dest="command")

    detect_p = subparsers.add_parser("detect", help="Detect project type")
    detect_p.add_argument("project_dir")

    gen_p = subparsers.add_parser("generate", help="Generate logging config")
    gen_p.add_argument("project_dir")
    gen_p.add_argument("--python", action="store_true")
    gen_p.add_argument("--node", action="store_true")
    gen_p.add_argument(
        "--framework",
        choices=["flask", "fastapi", "django", "express", "nextjs", "fastify"],
    )
    gen_p.add_argument("--output", help="Output filename")

    args = parser.parse_args()

    if args.command == "detect":
        info = detect_project(Path(args.project_dir))
        print(json.dumps(info, indent=2))
    elif args.command == "generate":
        lang = "python" if args.python else "node" if args.node else None
        if not lang:
            info = detect_project(Path(args.project_dir))
            lang = info["languages"][0] if info["languages"] else "python"
        config = generate_config(
            Path(args.project_dir), lang, args.framework, args.output
        )
        if not args.output:
            print(config)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
